# Change these first
owner: gezellligheid # Your GitHub organization or username, where this repository lives
repo: bandithemepark-upptime # The name of this repository


sites:
  - name: www.bandithemepark.net
    url: https://www.bandithemepark.net
  - name: play.bandithemepark.net
    url: https://api.mcsrvstat.us/2/play.bandithemepark.net
    __dangerous__body_down_if_text_missing: '"online":true'
  - name: api.bandithemepark.net
    url: https://api.bandithemepark.net/
    __dangerous__body_down_if_text_missing: '{"status":"ok"}'
    expectedStatusCodes:
      - 200
  - name: MQTT broker
    url: 54.36.178.219
    port: 1883
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bandithemepark.net
  # baseUrl: /bandithemepark-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BandiThemepark Status
  introTitle: "BandiThemepark Status"
  introMessage: ""
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
